services:
  app:
    build: ./app
    ports:
      - ${HOST_PORT}:80
    restart: ${RESTART_POLICY}
    volumes:
      - .:/go/src
    environment:
      - GIN_MODE=${SERVER_ENV}
    command: ${SERV_COMMAND:-go run .}
